model: UniSRec

load_col:
  inter: [user_id, item_id, timestamp]

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

alias_of_item_id: ~
enable_scaler: False

loss_type: CE
train_neg_sample_args: ~

freeze_plm: False
learning_rate: 1e-4
train_batch_size: 512
epochs: 100
stopping_step: 1000
eval_step: 1
pretrained_model_path: saved/UniSRec-best-17-12.pth


device: cuda