model: UniSRec

load_col:
  inter: [user_id, item_id, timestamp]

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

alias_of_item_id: ~
enable_scaler: False

loss_type: CE
train_neg_sample_args: ~

learning_rate: 2e-5
optimizer: AdamW
lr_scheduler: CosineAnnealingLR
T_max: 100
eta_min: 1e-6

train_batch_size: 512
epochs: 100
stopping_step: 15
eval_step: 1
pretrained_model_path: saved/UniSRec-best-17-12.pth


device: cuda